# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Too Long; Do Read

description:      'I am not just talking crap'
url:              http://tldr.nu

author:
  name:           'Ar0xA'
  url:            https://twitter.com/Ar0xA

paginate:         5