# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Too Long Do Read
tagline:          'Random Rantings'
description:      'Warning: security related braindumps by <a href="https://twitter.com/Ar0xA" target="_blank">Ar0xA</a>'
url:              http://tldr.nu

author:
  name:           'Ar0xA'
  url:            https://twitter.com/Ar0xA

paginate:         5

# Custom vars
#version:          2.0.0

github:
#  repo:           https://github.com/poole/hyde