# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ar0xA
tagline:          'Random Rantings'
description:      'A simple small little blog.'
url:              http://tldr.nu

author:
  name:           'Ar0xA'
  url:            https://twitter.com/Ar0xA

paginate:         5

# Custom vars
#version:          2.0.0

github:
#  repo:           https://github.com/poole/hyde