permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
#gems
gems: [jekyll-paginate]

paginate:         5



paginate: 10
paginate_path: ":num"
baseurl: ""



title: "Too Long; Do Read"
email: "ar0xa@tldr.nu"
description: "I am not <u>just</u> talking crap"
github_username:  "ar0xa"



url: "https://tldr.nu"
#imgrepo: "https://tldr.nu/static/img"
#url: "http://91.243.75.59:4002"

