# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Too Long; Do Read

description:      'I am not <u>just</u> talking crap'
url:              https://tldr.nu

author:
  name:           'Ar0xA'
  url:            https://twitter.com/Ar0xA

paginate:         5